name: Integration
on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Versionando de java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          architecture: x64
          distribution: "adopt"

      - name: Descargar dependencias maven
        run:  |
          mvn clean
          echo "Descargando dependencias"
      - name: Cache maven packages
        uses: actions/cache@v2
        env:
          cache-name: java-github-actions
        with:
          path: ~/.m2
          key:  java-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: java-${{ env.cache-name }}
  test-integration:
    runs-on:  ubuntu-latest
    needs:  build
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v2
        env:
          cache-name: java-github-actions
        with:
          path: ~/.m2
          key: java-${{env.cache-name }}-${{hashFiles('**/pom.xml') }}
          restore-keys: java-${{env.cache-name }}
      - name: Compilar
        run: mvn verify
      - name: Extraer reporte
        uses: actions/upload-artifact@v3
        with:
          name: prueba-actions
          path: |
            target/**